name: Build and Push (on-demand) dev Docker images to Docker Hub

on: workflow_dispatch

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0
        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.2.1
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Command Runner - Build and push Docker image
        uses: docker/build-push-action@v3.2.0
        with:
          context: ./Dockerfiles/CommandRunner
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/devenv4wpcommandrunner:latest-dev

      - name: PHP 7.4 - Build and push Docker image
        uses: docker/build-push-action@v3.2.0
        with:
          context: ./Dockerfiles/php/7.4
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/devenv4wpphp:7.4-dev

      - name: PHP 8.0 - Build and push Docker image
        uses: docker/build-push-action@v3.2.0
        with:
          context: ./Dockerfiles/php/8.0
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/devenv4wpphp:8.0-dev

      - name: PHP 8.1 - Build and push Docker image
        uses: docker/build-push-action@v3.2.0
        with:
          context: ./Dockerfiles/php/8.1
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/devenv4wpphp:8.1-dev

      - name: PHP 8.2 - Build and push Docker image
        uses: docker/build-push-action@v3.2.0
        with:
          context: ./Dockerfiles/php/8.2
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/devenv4wpphp:8.2-dev